name: rem_mm
description: An AI-powered fantasy football assistant using a RAG architecture with Gemini and Supabase.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Supabase Flutter SDK: Handles Auth, Database queries, and calling Edge Functions.
  # This is the primary client for our entire backend.
  supabase_flutter: ^2.5.0

  # Lightweight HTTP Client: Used for simple, direct GET requests to the public
  # Sleeper API. This will primarily be used in the backend Edge Functions, but
  # can be used in the app for non-critical data.
  http: ^1.2.1

  # State Management: A robust solution for managing app state, especially useful
  # for handling streams of data from Supabase and updating the UI reactively.
  flutter_riverpod: ^3.0.3
  
  # Secure Environment Variables: Manages Supabase URL and Anon Key without
  # hard-coding them into the app.
  envied: ^1.3.1

  # Google Fonts for custom typography
  google_fonts: ^6.1.0

  # JSON serialization
  json_annotation: ^4.9.0
  
  # Immutable data classes
  freezed_annotation: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  # Code generators for our dependencies. Build_runner will use these to
  # generate necessary boilerplate code.
  envied_generator: ^1.3.1
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.13
  
  # JSON and freezed code generation
  json_serializable: ^6.8.0
  freezed: ^3.2.3

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
